version: '3.7'
services:
  arbiter:
      image: containers.intersystems.com/intersystems/arbiter:2022.1.0.209.0
      init: true
      command: 
        - /usr/local/etc/irissys/startISCAgent.sh 2188
      networks:
        app_net:
          ipv4_address: 172.16.238.10
  mirrorA:
    container_name: mirrorA
    hostname: mirrorA
    image: containers.intersystems.com/intersystems/iris:2022.1.0.209.0
    depends_on:
      - arbiter
    volumes:
      - ./irisA:/ISC
      - ./:/ISC/utiles
    environment:
      - ISC_DATA_DIRECTORY=/ISC/install
      - IRIS_hostname=mirrorA
    ports:
      - "9092:52773"
    networks:
      app_net:
        ipv4_address: 172.16.238.20
    command:
      --check-caps false
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
    
  mirrorB:
    container_name: mirrorB
    hostname: mirrorB
    image: containers.intersystems.com/intersystems/iris:2022.1.0.209.0
    depends_on:
      - mirrorA
    volumes:
      - ./irisB:/ISC
      - ./:/ISC/utiles
    environment:
      - ISC_DATA_DIRECTORY=/ISC/install
      - IRIS_hostname=mirrorB
    ports:
      - "9093:52773"
    networks:
      app_net:
        ipv4_address: 172.16.238.30
    command:
      --check-caps false
      --key /ISC/utiles/iris.key
      -a /ISC/utiles/installer.sh
networks:
  app_net:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
    